// Firestore collection names — matches CLAUDE.md section 6
export const COL_ORGANIZATIONS = 'organizations'
export const COL_USERS = 'users'
export const COL_PROJECTS = 'projects'
export const COL_LESSONS = 'lessons'
export const COL_JHA = 'jha'
export const COL_SAFETY_MANUALS = 'safetyManuals'
export const COL_TOOLBOX_TALKS = 'toolboxTalks'
export const COL_COMMUNICATIONS = 'communications'
export const COL_DAILY_REPORTS = 'dailyReports'
export const COL_TIMESHEETS = 'timesheets'
export const COL_CERTIFICATIONS = 'certifications'
export const COL_EQUIPMENT = 'equipment'
export const COL_ACTIVITY_FEED = 'activityFeed'
export const COL_LOCATIONS = 'locations'
export const COL_MUSTER_EVENTS = 'musterEvents'
